config/routes.rb
Rails.application.routes.draw do

  root 'main#index', as: :index

  post 'main/war' => 'main#set_user'
  get 'main/war' => 'main#war', as: :current
  get '/plan' => 'main#current_plan'
  get '/logout' => 'main#logout'
  
  patch 'main/estimate' => 'main#estimate'
  
  resources :wars do
    member do
      get 'plan'
      patch 'set_done'
      patch 'freeze'
      post 'result'
      post 'update_attack'
      get 'ajax_plan'
      get 'done'
    end
  end

end

app/models/war.rb
class War < ActiveRecord::Base
  has_many :warriors, dependent: :delete_all
  has_many :estimates

  def count
    @count || @count = self.warriors.size
  end
  
  def set_order(order)
    self.warriors = []
    index = 1
    order.each do |id|
      self.warriors.build(user: User.find(id), order: index)
      index = index + 1
    end
  end
  
  def update(params)
    set_order(params.delete :order)
    super
  end

  def current_score
    score = 0
    bases = Array.new(self.count + 1, 0)
    warriors.each do |w|
      w.plans.each do |p|
        bases[p.base] = [p.stars, bases[p.base]].max if p.state == 'done'
      end
    end
    bases.sum
  end
      
  def _warrior_busy(bases)
    bases.each do |b|
      return true if b == 'sure'
    end
    false
  end

  def strategy(taken)
    @ret = Hash.new
    sorted = self.warriors.sort { |a,b| b.index_avg <=> a.index_avg }
    attacked = Array.new
    taken.each do |w, bases|
      bases.each_with_index do |b,index|
        attacked[index] = 1 if %w(sure done).include? b
      end
    end
    sorted.each do |w|
      next if _warrior_busy(taken[w])
      next if w.done_attacks >= 2
      next_base = 1
      while next_base <= self.count && (taken[w][next_base] == "no" || attacked[next_base] || w.average(next_base-1) < 2.5)
        next_base += 1
      end
      next if next_base > self.count
      attacked[next_base] = 1
      @ret[w] = next_base
    end
    @ret
  end
end

app/controllers/wars_controller.rb
class WarsController < ApplicationController
  before_action :set_war, only: [:show, :edit, :update, :destroy,
                                 :plan, :update_attack, :ajax_plan,
                                 :freeze, :result, :done, :set_done]
  before_action :require_password, only: [:edit, :index, :create, :update, :freeze]

  def require_password
    unless @user.password
      redirect_to :index
    end
  end
  
  # GET /wars
  # GET /wars.json
  def index
    @wars = War.all
  end

  # GET /wars/1
  # GET /wars/1.json
  def show
  end

  # GET /wars/new
  def new
    @war = War.new
  end

  # GET /wars/1/edit
  def edit
  end

  # POST /wars
  # POST /wars.json
  def create
    filtered_params = war_params
    order = filtered_params.delete :order
    @war = War.new(filtered_params)
    @war.set_order(order)
    
    respond_to do |format|
      if @war.save
        format.html { redirect_to @war, notice: 'War was successfully created.' }
        format.json { render :show, status: :created, location: @war }
      else
        format.html { render :new }
        format.json { render json: @war.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wars/1
  # PATCH/PUT /wars/1.json
  def update
    respond_to do |format|
      if @war.update(war_params)
        format.html { redirect_to @war, notice: 'War was successfully updated.' }
        format.json { render :show, status: :ok, location: @war }
      else
        format.html { render :edit }
        format.json { render json: @war.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wars/1
  # DELETE /wars/1.json
  def destroy
    @war.destroy
    respond_to do |format|
      format.html { redirect_to wars_url, notice: 'War was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_attack
    @warriors.each do |w|
      next unless w.index.to_s == params[:index]
      if params[:state] == 'def'
        w.plans.where(base: params[:base]).delete_all
      else
        plan = w.plans.find_or_create_by(base: params[:base])
        plan.state = params[:state]
        plan.user = @user
        plan.save
      end
    end
    set_war
    ajax_plan
  end

  def _calc_plan
    @plan = Array.new
    taken = Hash.new
    @warriors.each do |w|
      taken[w] = Array.new(@war.count, nil)
      w.plans.each do |p|
        hash = {index: w.index, base: p.base, state: p.state}
        hash[:stars] = p.stars if p.state == 'done'
        @plan.append(hash)
        taken[w][p.base] = p.state unless p.state == 'done' && p.stars != 3
      end
    end
    taken
  end
  
  def ajax_plan
    taken = _calc_plan
    @war.strategy(taken).each do |w,b|
      next if taken[w][b]
      @plan.append({index: w.index, base: b, state: 'sug'})
    end

    @missing = Array.new
    done_bases = Array.new
    nr_finished = Hash.new
    @plan.select { |p| p[:state] == 'done' }.each do |p|
      nr_finished[p[:index]] = (nr_finished[p[:index]] || 0) + 1
      done_bases << p[:base] if p[:stars] == 3
    end
    @finished = Array.new
    nr_finished.each { |index, nr|
      @finished << index if nr == 2 
    }
    @war.count.times do |i|
      i += 1
      if @plan.select { |p| p[:index] == i && p[:state] != 'no' }.empty?
        @missing.append("#index_#{i}")
      end
      
      if @plan.select { |p| p[:base] == i && %w(sure sug).include?(p[:state]) }.empty?
        next if done_bases.include? i
        @missing.append("#base_#{i}")
      end
    end
    render :ajax_plan
  end
  
  def plan
    if @war.done
      redirect_to done_war_path(@war) and return
    end
    @plan = []
  end

  def set_done
    unless @war.started && @user.name == 'Troyz'
      Rails.logger.error "not allowing set_done for #{@user.name}"
      redirect_to :current and return
    end

    @war.warriors.each do |w|
      keep = Array.new
      w.plans.each do |p|
        keep << w.estimates.where(base: p.base).all
      end
      keep.flatten!
      w.estimates.where.not(id: keep).delete_all
    end
    @war.done = true
    @war.save
    redirect_to done_war_path(@war)
  end
  
  def done
    unless @war.done
      redirect_to :current
    end
  end

  def freeze
    taken = _calc_plan
    @war.strategy(taken).each do |w,b|
      plan = w.plans.create(base: b, state: 'sure')
    end
    # ignore blacklist
    Plan.where(warrior_id: @war.warriors, state: 'no').delete_all
    @war.started = true
    @war.save
    redirect_to plan_war_path(@war)
  end

  def result
    plan = Plan.where(warrior_id: params[:index], base: params[:base]).first_or_create
    plan.state = 'done'
    plan.user = @user
    plan.th = params[:townhall] == 'true'
    plan.percent = params[:percent]
    plan.stars = 0
    if plan.percent == 100
      plan.stars = 3
      plan.th = true
    elsif plan.percent >= 50
      plan.stars = 1
      plan.stars += 1 if plan.th
    end
    plan.save
    render json: {}
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_war
      @war = War.includes(:warriors, warriors: [:estimates, :plans]).find(params[:id])
      @warriors = @war.warriors
      @warriors.each_with_index do |w,i|
        w.index = i + 1
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def war_params
      params[:war].permit(:title, :order => [])
    end
end

app/helpers/wars_helper.rb
module WarsHelper
end

app/views/wars/_form.html.erb
<%= form_for(@war) do |f| %>
  <% if @war.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@war.errors.count, "error") %> prohibited this war from being saved:</h2>

      <ul>
      <% @war.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label(:title, "Titel des Krieges:") %>
  <%= f.text_field(:title) %>

  <div>
  Teilnehmer:
  </div>
  
  <select multiple="multiple" id="warriors" name="war[order][]">
    <% User.order(:name).each do |u| %>
       <% selected = u.warrior_in?(@war) ? ' selected' : '' %>
       <option value='<%= u.id %>'<%= selected %>><%= u.name %></option>
    <% end %>
  </select>

  <%= javascript_tag "setupWarriors();" %>
  
  <div class="actions">
    <%= f.submit "Fertig" %>
  </div>
<% end %>

app/views/wars/done.html.haml
- @war.warriors.each do |w|
  - w.plans.each do |p|
    - next unless p.state == 'done'
    %h4
      Angriff von
      = w.user_name
      auf
      = p.base
      ergab:
      = p.stars
    %ul
      - w.estimates.each do |e|
        - next if e.base != p.base
        %li
          = e.user_name
          schätzte
          = e.stars

app/views/wars/edit.html.erb
<h1>Editing War</h1>

<%= render 'form' %>

<%= link_to 'Show', @war %> |
<%= link_to 'Back', wars_path %>

app/views/wars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wars</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wars.each do |war| %>
      <tr>
        <td><%= link_to war.title, war %></td>
        <td><%= link_to 'Edit', edit_war_path(war) %></td>
        <td><%= link_to 'Destroy', war, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<td><%= link_to 'Fertig', set_done_war_path(war), method: :patch, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New War', new_war_path %>

app/views/wars/new.html.erb
<h1>New War</h1>

<%= render 'form' %>

<%= link_to 'Back', wars_path %>

app/views/wars/plan.html.haml
%h1
  Plan für Krieg
  = @war.title
  - if @war.started
    = "(angefangen, #{@war.current_score}*)"

- content_for :ready_function, "hide_done = #{params[:nohide] ? 'false' : 'true'};"

%table.table{id: 'plan', data: {'post-url': update_attack_war_path(@war),
           'get-url': ajax_plan_war_path(@war) }, class: 'table table-bordered table-hover hide'}
  %thead
    %td Name
    - @war.count.times do |i|
      %td{id: "base_#{i+1}", class: "text-center text-muted base_#{i+1}"}= i +1
  %tbody
    - @warriors.each do |w|
      %tr{class: "index_#{w.index}"}
        - done = w.done_attacks
        - done = done > 0 ? " (#{w.done_attacks})" : ''
        %td{class: 'bg-success text-nowrap text-muted', id: "index_#{w.index}", data: { name: w.user_name, wid: w.id }}= "#{w.index}. #{w.user_name} #{done}"
        - w.averages.each_with_index do |e,base|
          - marked = 'attack'
          - id = "#{w.index}_#{base+1}"
          %td{class: "text-center attack base_#{base + 1}", id: "T_#{id}", data: { index: w.index, base: base + 1}}
            .avg= e.to_s.gsub('.0','')
          - tt = "<div class='text-nowrap'><big>#{w.user_name} attack on #{base + 1}</big></div>"
          - tt += "<ul class='estimate-list'>"
          - estimates = 0
          - w.each_estimate(base+1) do |b|
            - tt << "<li class='text-nowrap'>#{b.stars} #{User.name_for(b.user_id)}</li>"
            - estimates += 1
          - tt << "</ul>"
          - if estimates > 0
            - content_for :ready_function do
              $("#T_#{id} div.avg").tooltip({'title': "#{tt.html_safe}", html: true });

- unless @war.started
  - content_for :ready_function do
    setupPlan();
  - if @user.password
    = form_for @war, url: {action: "freeze"} do |f|
      = f.submit "Freeze Plan", data: { confirm: "Geht's los?" }
- else
  - content_for :ready_function do
    setupStartedWar();

- content_for :ready_function do
  $('#plan').removeClass('hide');

%div{class: "modal fade", id: "finishedModal", role: "dialog", 'aria-labelledby': "exampleModalLabel"}
  %div{class: "modal-dialog", role: "document"}
    .modal-content
      .modal-header
        %button{type: "button", class: "close", 'data-dismiss': "modal", 'aria-label': "Close"}
          %span{'aria-hidden': "true"}
            &times;
        %h4{class: "modal-title"}
          Gib das Ergebnis des Angriffs von
          %span{id: 'warrior-name'}
          auf die
          %span{id: 'enemy-name'}
          ein.

      = form_tag({ action: "result" }, { id: 'result_form' }) do
        .modal-body
          %input{type: "hidden", class: "form-control", disabled: 1, id: "warrior-id"}
          %input{type: "hidden", class: "form-control", disabled: 1, id: "enemy-index"}
          .form-group
            <label for="percent" name="percent" class="control-label">Prozent:</label>
            %input{type: "text", class: "form-control", id: "percent"}

          .form-group
            %div.btn-group{'data-toggle': "buttons"}
              %label{class: "btn btn-success"}
                %input{type: "checkbox", autocomplete: "off", id: 'townhall'} Rathaus erledigt?

        .modal-footer
          <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
          = submit_tag 'Speichern', class: "btn btn-primary", id: 'submit_result'

app/views/wars/show.html.erb
<p id="notice"><%= notice %></p>

<p>Titel des Krieges: <%= @war.title %>
</p>

<h3>Teilnehmer:</h3>

<ol>
<% @war.warriors.order(:order).each do |w| %>
<li><%= w.user.name %></li>
<% end %>
</ol>

<%= link_to 'Edit', edit_war_path(@war) %> |
<%= link_to 'Back', wars_path %>